version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}-cdn
    env_file:
      - ../../../.env   
    build:
      context: ../../
      dockerfile: infrastructure/docker/java.dockerfile
      target: buildcdn
